@cmpcbo-815 @client @createClientMVP @regression @sprint15
Feature: CMPCBO-815 - Alternative Check and Confirm Client-Create Client by Colleague
  As a colleague when setting up the Client agreement I am able to view all details entered in the
  Create Client process prior to submitting for approval.
  I am also able to Edit the client details from the summary page and see the page that the data was entered on.

  @cmpcbo815-01
  Scenario: Colleague captured the client details including the Primary Admin Details and navigated to the check
            and confirm page where the client's details are displayed as read only.
    #Client
    Given I navigate to the "colleague_create_client_url" page
    When I entered "Volvo UK" in "client_name_entry_field"
    And I entered "8025489523" in "bp_id_entry_field"
    And I entered "5060708765" in "cmd_id_entry_field"
    And I entered "Address Line 1" in "address_line1_entry_field"
    And I entered "Address Line 2" in "address_line2_entry_field"
    And I entered "Address Line 3" in "address_line3_entry_field"
    And I entered "London" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2DA" in "postcode_entry_field"
    And I click on "next_button"
    And I select by Index "1" from the dropdown "service_package_name"
    And I click on "next_button"
    #First Admin
    And I select by Text "Mr" from the dropdown "title_entry_field"
    And I entered "DanielOne" in "firstName_entry_field"
    And I entered "JonesOne" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testOne@test.com" in "email_entry_field"
    And I entered "testOne@test.com" in "confirm_email_entry_field"
    And I entered "098765433111" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA1 1FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "popup_second_admin_confirmation"
    And I should see Sub Heading "Second primary administrator details" at "second_primary_admin_details_heading"
    #Secondary Admin
    And I select by Text "Dr" from the dropdown "title_entry_field"
    And I entered "DanielTWO" in "firstName_entry_field"
    And I entered "JonesTWO" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testTWO@test.com" in "email_entry_field"
    And I entered "testTWO@test.com" in "confirm_email_entry_field"
    And I entered "098765433222" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2FA" in "postcode_entry_field"
    When I click on "next_button"
    Then I should see the "cc_client_details_label" is visible
    Then I should see the "cc_edit_client_details" is visible
    Then I should see the "cc_bpid_label" is visible
    Then I should see the "cc_client_details_label" is visible
    Then I should see the "cc_client_name_label" is visible
    Then I should see the "cc_client_address_label" is visible
    Then I should see the "cc_client_settings_label" is visible
    Then I should see the "cc_client_name_label" is visible
    Then I should see the "cc_service_package_label" is visible
    Then I should see the "cc_first_primary_admin_details_label" is visible
    Then I should see the "cc_second_primary_admin_details_label" is visible

  @cmpcbo815-02
  Scenario: Correct details are captured on check and confirm page
    Given I navigate to the "colleague_create_client_url" page
    Given I entered "Volvo UK" in "client_name_entry_field"
    And I entered "8025489523" in "bp_id_entry_field"
    And I entered "5060708765" in "cmd_id_entry_field"
    And I entered "Address Line 1" in "address_line1_entry_field"
    And I entered "Address Line 2" in "address_line2_entry_field"
    And I entered "Address Line 3" in "address_line3_entry_field"
    And I entered "London" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2DA" in "postcode_entry_field"
    And I click on "next_button"
    And I select by Index "1" from the dropdown "service_package_name"
    And I click on "next_button"
    #First Admin
    And I select by Text "Mr" from the dropdown "title_entry_field"
    And I entered "DanielOne" in "firstName_entry_field"
    And I entered "JonesOne" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testOne@test.com" in "email_entry_field"
    And I entered "testOne@test.com" in "confirm_email_entry_field"
    And I entered "098765433111" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA1 1FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "popup_second_admin_confirmation"
    And I should see Sub Heading "Second primary administrator details" at "second_primary_admin_details_heading"
    #Secondary Admin
    And I select by Text "Dr" from the dropdown "title_entry_field"
    And I entered "DanielTWO" in "firstName_entry_field"
    And I entered "JonesTWO" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testTWO@test.com" in "email_entry_field"
    And I entered "testTWO@test.com" in "confirm_email_entry_field"
    And I entered "098765433222" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2FA" in "postcode_entry_field"
    When I click on "next_button"
    Then I should see a "cc_client_name_cc" as "Volvo UK"
    Then I should see a "cc_bpid_cc" as "8025489523"
    Then I should see a "cc_cmdid_cc" as "5060708765"
    Then I should see a "cc_clint_postcode_cc" as "FA2 2DA"
    Then I should see a "cc_clint_country_cc" as "United Kingdom"
    Then I should see a "cc_service_package_cc" as "Accounts, Balances and Reporting"
    Then I should see a "cc_first_primary_admin_name" as "Mr DanielOne JonesOne"
    Then I should see a "cc_first_primary_admin_email" as "testOne@test.com"
    Then I should see a "cc_first_primary_phone_number" as "098765433111"
    Then I should see a "cc_first_primary_country" as "United Kingdom"
    Then I should see a "cc_second_primary_admin_name" as "Dr DanielTWO JonesTWO"
    Then I should see a "cc_second_primary_admin_email" as "testTWO@test.com"
    Then I should see a "cc_second_primary_phone_number" as "098765433222"
    Then I should see a "cc_second_primary_country" as "United Kingdom"

  @cmpcbo815-03
  Scenario: Client Details Edit Button
    Given I navigate to the "colleague_create_client_url" page
    Given I entered "Volvo UK" in "client_name_entry_field"
    And I entered "8025489523" in "bp_id_entry_field"
    And I entered "5060708765" in "cmd_id_entry_field"
    And I entered "Address Line 1" in "address_line1_entry_field"
    And I entered "Address Line 2" in "address_line2_entry_field"
    And I entered "Address Line 3" in "address_line3_entry_field"
    And I entered "London" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2DA" in "postcode_entry_field"
    And I click on "next_button"
    And I select by Index "1" from the dropdown "service_package_name"
    And I click on "next_button"
    #First Admin
    And I select by Text "Mr" from the dropdown "title_entry_field"
    And I entered "DanielOne" in "firstName_entry_field"
    And I entered "JonesOne" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testOne@test.com" in "email_entry_field"
    And I entered "testOne@test.com" in "confirm_email_entry_field"
    And I entered "098765433111" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA1 1FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "popup_second_admin_confirmation"
    And I should see Sub Heading "Second primary administrator details" at "second_primary_admin_details_heading"
    #Secondary Admin
    And I select by Text "Dr" from the dropdown "title_entry_field"
    And I entered "DanielTWO" in "firstName_entry_field"
    And I entered "JonesTWO" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testTWO@test.com" in "email_entry_field"
    And I entered "testTWO@test.com" in "confirm_email_entry_field"
    And I entered "098765433222" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "cc_edit_client_details"
    Then I should see Page Heading "Create a new client" as "create_client_page_heading"

  @cmpcbo815-04
  Scenario: Service Package Edit Button
    Given I navigate to the "colleague_create_client_url" page
    Given I entered "Volvo UK" in "client_name_entry_field"
    And I entered "8025489523" in "bp_id_entry_field"
    And I entered "5060708765" in "cmd_id_entry_field"
    And I entered "Address Line 1" in "address_line1_entry_field"
    And I entered "Address Line 2" in "address_line2_entry_field"
    And I entered "Address Line 3" in "address_line3_entry_field"
    And I entered "London" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2DA" in "postcode_entry_field"
    And I click on "next_button"
    And I select by Index "1" from the dropdown "service_package_name"
    And I click on "next_button"
    #First Admin
    And I select by Text "Mr" from the dropdown "title_entry_field"
    And I entered "DanielOne" in "firstName_entry_field"
    And I entered "JonesOne" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testOne@test.com" in "email_entry_field"
    And I entered "testOne@test.com" in "confirm_email_entry_field"
    And I entered "098765433111" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA1 1FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "popup_second_admin_confirmation"
    And I should see Sub Heading "Second primary administrator details" at "second_primary_admin_details_heading"
    #Secondary Admin
    And I select by Text "Dr" from the dropdown "title_entry_field"
    And I entered "DanielTWO" in "firstName_entry_field"
    And I entered "JonesTWO" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testTWO@test.com" in "email_entry_field"
    And I entered "testTWO@test.com" in "confirm_email_entry_field"
    And I entered "098765433222" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2FA" in "postcode_entry_field"
    And I click on "next_button"
    When I click on "cc_edit_service_package"
    Then I should see Page Heading "Select service package" as "select_service_page_heading"

  @cmpcbo815-05
  Scenario: First Primary Admin Edit Button
    Given I navigate to the "colleague_create_client_url" page
    Given I entered "Volvo UK" in "client_name_entry_field"
    And I entered "8025489523" in "bp_id_entry_field"
    And I entered "5060708765" in "cmd_id_entry_field"
    And I entered "Address Line 1" in "address_line1_entry_field"
    And I entered "Address Line 2" in "address_line2_entry_field"
    And I entered "Address Line 3" in "address_line3_entry_field"
    And I entered "London" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2DA" in "postcode_entry_field"
    And I click on "next_button"
    And I select by Index "1" from the dropdown "service_package_name"
    And I click on "next_button"
    #First Admin
    And I select by Text "Mr" from the dropdown "title_entry_field"
    And I entered "DanielOne" in "firstName_entry_field"
    And I entered "JonesOne" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testOne@test.com" in "email_entry_field"
    And I entered "testOne@test.com" in "confirm_email_entry_field"
    And I entered "098765433111" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA1 1FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "popup_second_admin_confirmation"
    And I should see Sub Heading "Second primary administrator details" at "second_primary_admin_details_heading"
    #Secondary Admin
    And I select by Text "Dr" from the dropdown "title_entry_field"
    And I entered "DanielTWO" in "firstName_entry_field"
    And I entered "JonesTWO" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testTWO@test.com" in "email_entry_field"
    And I entered "testTWO@test.com" in "confirm_email_entry_field"
    And I entered "098765433222" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "cc_edit_first_primary_admin"
    When I click on "primary_admin_plus_icon"
    Then I should see Page Heading "First primary administrator details" as "primary_admin_plus_details"

  @cmpcbo815-06
  Scenario: Second Primary Admin Edit Button
    Given I navigate to the "colleague_create_client_url" page
    Given I entered "Volvo UK" in "client_name_entry_field"
    And I entered "8025489523" in "bp_id_entry_field"
    And I entered "5060708765" in "cmd_id_entry_field"
    And I entered "Address Line 1" in "address_line1_entry_field"
    And I entered "Address Line 2" in "address_line2_entry_field"
    And I entered "Address Line 3" in "address_line3_entry_field"
    And I entered "London" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2DA" in "postcode_entry_field"
    And I click on "next_button"
    And I select by Index "1" from the dropdown "service_package_name"
    And I click on "next_button"
    And I select by Text "Mr" from the dropdown "title_entry_field"
    And I entered "DanielOne" in "firstName_entry_field"
    And I entered "JonesOne" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testOne@test.com" in "email_entry_field"
    And I entered "testOne@test.com" in "confirm_email_entry_field"
    And I entered "098765433111" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA1 1FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "popup_second_admin_confirmation"
    And I should see Sub Heading "Second primary administrator details" at "second_primary_admin_details_heading"
    And I select by Text "Dr" from the dropdown "title_entry_field"
    And I entered "DanielTWO" in "firstName_entry_field"
    And I entered "JonesTWO" in "lastName_entry_field"
    And I entered "QEOne" in "jobTitle_entry_field"
    And I entered "testTWO@test.com" in "email_entry_field"
    And I entered "testTWO@test.com" in "confirm_email_entry_field"
    And I entered "098765433222" in "phone_entry_field"
    And I entered "2FA" in "address_line1_entry_field"
    And I entered "London" in "address_line2_entry_field"
    And I entered "Liverpool Street" in "town_entry_field"
    And I select by Text "United Kingdom" from the dropdown "country_entry_field"
    And I entered "FA2 2FA" in "postcode_entry_field"
    And I click on "next_button"
    And I click on "cc_edit_second_primary_admin"
    When I click on "secondary_admin_plus_icon"
    Then I should see Page Heading "Second primary administrator details" as "secondary_admin_plus_details"

